### PR TITLE
Remove config on uninstall

### PR DESCRIPTION
**Pull request by zackdavies**
Relates to https://github.com/localgovdrupal/localgov_news/issues/94 . Remove Pathauto settings, and add a field dependency on the module so that it uninstalls correctly.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Thanks @zackdavies I can confirm this allows uninstall and reinstall.
I noticed that `pathauto.pattern.localgov_newsroom.yml` doesn't have the enforced dependency, where as `pathauto.pattern.localgov_news.yml` does. Maybe thats whats causing the error? There are two content types, news article and newsroom.

**Comment by zackdavies** [comment]
Thanks Andy. Silly me, I've updated the YML and removed the uninstall hook and it works as intended.

**Review by andybroomfield — APPROVED** [review]
Can confirm localgov_news can be uninstalled and reinstalled.
I do get error (though not releated to this PR). that uninstalling news when there is existing news articles. I think maybe we should prevent localgov_news and other modules from uninstalling if they have content of there type installed.
Happy though for this PR to merge.

**Comment by zackdavies** [comment]
Thanks Andy. Yes, if there's existing content you run into problems, but that seems intentional and out of the scope of this ticket. Can I merge this now, or do we wait for Merge Tuesday?

**Comment by andybroomfield** [comment]
I thin this is mergable

**Pull request merged**
