### PR TITLE
Remove link_attributes dependancy (was : Update link_attributes to 2.x branch)

### LINKED ISSUE #115: Update Link attributes to the 2.x branch
See https://github.com/localgovdrupal/localgov/issues/752

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #115

Set min version to 2.1 as 1.x branch unsuported.

## What does this change?

~~Upgrades to 2.x branch~~
Now it removes the module.

## How to test

Along with https://github.com/localgovdrupal/localgov_services/pull/276 there should no longer be an unsupported module message.

## How can we measure success?

News links still can have custom attributes / classes.
No more unsupported module error messages.

Update: But there aren't any news links.

## Have we considered potential risks?

Standard module major upgrade risks apply.

## Images

n/a

## Accessibility

n/a

### CODE REVIEW

**Comment by andybroomfield** [comment]
I don't know where this is used on news, maybe it is redundant?

**Comment by ekes** [comment]
Yes I think this should be removed from this module. There are no link fields in the default install.

**Comment by ekes** [comment]
Unless it's menu links?

**Comment by ekes** [comment]
Can't see it doing anything with it there either.

**Pull request merged**
