### PR TITLE
Basic search with search API

### LINKED ISSUE #7: Use search API
Implement search API for news.

### LINKED ISSUE #9: Facets for news category and date
Add facet filtering on search results by category and news date (year).

### PR DESCRIPTION
**Pull request by danchamp**
Full text search for news with autocomplete using search API. This PR:

- Adds search server for news.
- Adds search index for news articles.
- Adds search index entity view display.
- Updates news search block to provide text search backed by index.
- Implements auto-complete, displaying titles of news articles matching input.
- Adds facets and blocks for date and category

Closes #7 Closes #9

### CODE REVIEW

**Comment by andybroomfield** [comment]
Is this ready for review as I keep seeing new code pushed. It's maybe better to keep the PR as draft until its ready?

**Comment by danchamp** [comment]
It is ready now @andybroomfield. I added the facets to this PR as a convenience for my testing, since they are dependent on the search index.

**Review by andybroomfield — APPROVED** [review]
The search works after adding news articles,
I see autocomplete is working and the facets using the taxonomy provided.
I have some queries about it using the topic terms and if news categories should be used instead?
I also would like to see tests for this feature as tests for news are a little thin right now.

screencapture-localgov-lndo-site-8000-news-search-2021-02-24-17_49_45
Screenshot 2021-02-24 at 5 49 27 pm

**Comment by danchamp** [comment]
Thanks @andybroomfield 

Re topic terms - there was discussion with the product group about this, and it was agreed that using the localgov topics vocabulary by default would be the most common use case to make it straightforward to surface related news on other content. The module shouldn't provide any barrier to swapping or extending the vocabs used for the field.

Re tests - completely agree. It's on my list for today, I'll update issue #4 with progress.

**Pull request merged**
