### PR TITLE
Add RSS feed for the news feed

### LINKED ISSUE #99: RSS feed
Required for some services to send automated newsletters eg GovDelivery

Possibly useful instructions here https://devcollaborative.com/blog/how-add-rss-feed-drupal-website

Requested by North Devon

### PR DESCRIPTION
**Pull request by andybroomfield**
FIx #99

Amends the news list view to provide an rss feed at /node/%node/feed.rss
and provides a link on the news list.

### CODE REVIEW

**Comment by andybroomfield** [comment]
I'm assuming the changes from re-exporting the view are what is expected, as this was done with the demo content installed. Added as draft for now for someone to have a second eye over it.

It will add 'Subscribe to News list' link at the bottom of the newsroom page which is provided by Drupal core, so either Localgov_base or custom themes will need to change this / add feed icons.

**Comment by andybroomfield** [comment]
The test fails because adding the feed does not bring the route in for the feed view, crashing the news search. This only happens on the test and adding `drupal_flush_all_caches()` does fix this locally, though that might not be the best way?

**Comment by andybroomfield** [comment]
Marking as ready for review as PHPStan fail resolved in #106.

**Comment by andybroomfield** [comment]
Not sure how to provide the update hook, though it is fairly straight forward to self implement by adding a feed display to the existing news view.

**Comment by andybroomfield** [comment]
Theres also the issue of the view title, I can't find a way of replacing it in the feed with the newsroom title so it either shows as News list or Subscribe to 4 (the node id of the newsroom). Closest I've come is adding this.
```php
function localgov_news_views_pre_render($view) {
  $view_id = $view->id();
  $style = $view->getStyle()->getPluginId();

  if ($view_id == 'localgov_news_list' && $style == 'rss') {
    $newsroom_node = Node::load($view->argument['localgov_newsroom_target_id']->getValue());
    $view->setTitle($newsroom_node->getTitle());
  }
}
```

**Comment by andybroomfield** [comment]
Solved by changing the argument from the field newsroom target_id to the node id via a relationship to the newsroom, which allows the use of the Nid argument filter which displays the correct title.

**Comment by ekes** [comment]
I'm missing promoted news items from the feed? I guess they should be included at the top (out of order).
Also should the pubDate be the localgov_news_date

I don't wonder if this shouldn't also be a thing we could push upgrades for, but that could be a separate issue/mr.

**Comment by finnlewis** [comment]
@andybroomfield asking about update hook, how do we deploy this update to existing sites?

@ekes suggests: 
 - hook_update to check if the view is in the default state, if it has not been changed, update the view. If it has changed, leave it alone.

But @andybroomfield pointed out that the default view is probably quite old, so on a current 10.2.2 site, the view config is probably already different from the initial install.

**Comment by andybroomfield** [comment]
Pushed amended view which includes the promoted news articles.
The published date will be a bit more tricky.

Example hacky version (not how I would implement).
```php
function localgov_news_preprocess_views_view_row_rss(&$variables) {
  $nid = $variables['row']->nid;
  $node = Node::load($nid);
  $pub_date = gmdate('r', strtotime($node->localgov_news_date->value));
  $variables['item_elements'][0]['value'] = $pub_date;
}
```

This allows changing the pubDate key, which is an element in the `$variables['item_elements']` array. May not always be the first one though so need to check the `['key']` element (the array conists of an array with `'key' => 'pubDate', 'value' => 'Thu, 01 Feb 2024 00:00:00 +0000'`).

The new published date is just a simple date field, no time, so would always read midnight unless we extended it.

**Comment by ekes** [comment]
@ekes to check "hacky"

**Comment by ekes** [comment]
Having a look at ` Drupal\node\Plugin\views\row\Rss` seems it's now handily sent through build with the elements attached https://git.drupalcode.org/project/drupal/-/blob/10.2.x/core/modules/node/src/Plugin/views/row/Rss.php?ref_type=heads#L108 so that seems the neatest point to do it 0e53a78

Doing so pointed out to me we're also putting the username of the account that created the item in it. Which is probably suboptimal as it's not something we're exposing on the frontend. I don't know if anyone finds this important? It's easy to change, but what to? it would need some configuration somewhere so some set it (per newsroom?).

**Comment by ekes** [comment]
Removing the 'author' (creator) completely might also be an option. I don't think it's required by the spec.

The body of the item also presently has the title repeated, the authoring information, and the created date in the HTML. This probably needs tidying up as well.

```
<item>
<title>Title</title>
<link>https://lgd3.ddev.site/newsroom/2024/title</link>
<description> <span>Title</span> <span><a title="View user profile." href="https://lgd3.ddev.site/user/1">admin</a></span> <span><time datetime="2024-02-20T14:53:13+00:00" title="Tuesday 20 February 2024 at 2:53pm">Tue 20/02/2024 2:53pm</time> </span> <div class="field field--name-localgov-news-date field--type-datetime field--label-hidden field__item">3 September 2024</div> <div class="text-content clearfix field field--name-body field--type-text-with-summary field--label-hidden field__item"><p>Body text</p> </div> </description>
<pubDate>Tue, 03 Sep 2024 12:00:00 +0000</pubDate>
<dc:creator>admin</dc:creator>
<guid isPermaLink="false">2 at https://lgd3.ddev.site</guid>
</item>
```

**Comment by willguv** [comment]
Hi @ekes I wouldn't remove the author completely as occasionally news articles have named authors. It's rare but I've seen it happen.

Think it's better to follow the suggestions in chat to have a generic author eg "Scarfolk Council news team"

**Comment by ekes** [comment]
@willguv At the moment we don't have the concept of author in News. By which I mean there is no way of setting, or displaying, an author field on a particular news item. That would mean adding a field to all news items, and making a way of displaying it in the front end too I think.

Without adding that the potential options I can think of are:
- simple: no author;
- a bit more complicated: replace the author with the site name;
- a bit more complicated: add an author field onto the news channel node, use that value on all articles. Explain somehow the purpose of this field, that isn't shown in the front end, to the user creating the news channel node.

**Comment by ekes** [comment]
Discussion in Merge Tuesday: Unset creator for now, and create new issue to make configurable.

**Comment by andybroomfield** [comment]
There is an oddity here as order of the items in the feed is out of order with the page, as I think its dependent on the post date which currently they are all at midnight.

**Comment by andybroomfield** [comment]
Ready for re-review. 
I've re-added a fix to change the feeds argument to the newsroom id via a relationship to the newsroom instead of the other way round in the main view, as that is the way to get the newsroom title for the feed link.

I've removed dc:creator in the RSS feed.

I've added an extra sort by the created date after the override date field, this is to keep the news items in the same order as the news page view (we need to look at override dates in the future).

No update hook for existing as we need a way to compare the default view config which is quite far out of date with updates applied by Drupal itself. The best I can reccomend here is for sites that want to add the RSS feed to get the config file in localgov_news/config/install/views.view.localgov_news_list.yml and import that via configuration -> development -> import -> single item. Then they will need to re-apply any customisations they have done.

**Comment by ekes** [comment]
Have to say I was thinking that having the promoted items still at the top of the RSS feed was fine; but I don't think it's so important either way.

Rest looks good.

**Review by ekes — APPROVED** [review]

**Comment by finnlewis** [comment]
Great! Letting @ekes do the merge.

**Pull request merged**
