### PR TITLE
Feature/5 news schema

### LINKED ISSUE #5: Implement NewsArticle structured data from schema.org
Implementing structured data for news will improve discoverability and SEO.

The relevant schema is defined at: https://schema.org/NewsArticle

This could be achieved most easily by using the [**Schema.org Metatag module**](https://www.drupal.org/project/schema_metatag), a Metatag sub-module which implements JSON LD.

Google has [expressed a preference](http://www.thesempost.com/json-ld-googles-preferred-structured-data-markup/) for JSON LD over markup microdata.

The module has direct support for the NewsArticle object type

There will also be other use cases for the module within LocalGov Drupal, including [Events](https://schema.org/Event), Services, and Directories.

An alternative would be to use **markup microdata** in templates. Downsides to this approach include the need to replicate the relevant attributes if templates are over-ridden, amendments cannot be made through the Drupal UI, and Google's preference for JSON LD.

The validity of output should be tested with Google's [Rich Results Test Tool](https://search.google.com/test/rich-results)

### PR DESCRIPTION
**Pull request by danchamp**
This PR adds the [NewsArticle schema](https://schema.org/NewsArticle) to LocalGov Drupal news articles, as JSON-LD in the document <head>. Closes #5 

Validated against Google's [Rich Results Test Tool](https://search.google.com/test/rich-results), using local tests and this publicly accessible example:

- ["Heartbreaking" - statement on new national lockdown](https://dev.londoncouncils.gov.uk/news/2021/heartbreaking-statement-new-national-lockdown)

Validation results:

- https://search.google.com/test/rich-results?id=eMEH--GY4w_looLnOzFDWw

Notes:

- The 'about' element only includes the first category related to a news article.
- If the category contains a comma, the category is exploded into multiple 'about' elements which expects a comma-delimited list of terms. As a temporary fix the module removes commas from categories using hook_tokens_alter()
- Uses the source image URL at full resolution (it's the responsibility of consuming services to resize the image if required).

### CODE REVIEW

**Comment by andybroomfield** [comment]
Have managed to install and I see this in the head
````html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "NewsArticle",
            "headline": "LGBTQ+ History Month - \u0026#039;Self-awareness\u0026#039;",
            "name": "LGBTQ+ History Month - \u0026#039;Self-awareness\u0026#039;",
            "description": "LGBT Month",
            "image": {
                "@type": "ImageObject",
                "representativeOfPage": "True",
                "url": "http://localgov.lndo.site:8000/sites/default/files/2021-02/thumb-LGBTQHM21-self-awareness.png",
                "width": "244",
                "height": "183"
            },
            "datePublished": "2021-02-24",
            "dateModified": "2021-02-24",
            "hasPart": {
                "@type": "WebPageElement",
                "isAccessibleForFree": "True"
            },
            "isAccessibleForFree": "True",
            "author": {
                "@type": "Organization",
                "@id": "http://localgov.lndo.site:8000/",
                "name": "Drush Site-Install",
                "url": "http://localgov.lndo.site:8000/"
            },
            "publisher": {
                "@type": "Organization",
                "@id": "http://localgov.lndo.site:8000/",
                "name": "Drush Site-Install",
                "url": "http://localgov.lndo.site:8000/"
            },
            "mainEntityOfPage": "http://localgov.lndo.site:8000/news/2021/lgbtq-history-month-self-awareness"
        }
    ]
}
</script>
````

That looks ok on first glance, though may require someone from product group to review if those are the correct tags.

**Comment by andybroomfield** [comment]
Have managed to install and I see this in the head
````html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "NewsArticle",
            "headline": "LGBTQ+ History Month - \u0026#039;Self-awareness\u0026#039;",
            "name": "LGBTQ+ History Month - \u0026#039;Self-awareness\u0026#039;",
            "description": "LGBT Month",
            "image": {
                "@type": "ImageObject",
                "representativeOfPage": "True",
                "url": "http://localgov.lndo.site:8000/sites/default/files/2021-02/thumb-LGBTQHM21-self-awareness.png",
                "width": "244",
                "height": "183"
            },
            "datePublished": "2021-02-24",
            "dateModified": "2021-02-24",
            "hasPart": {
                "@type": "WebPageElement",
                "isAccessibleForFree": "True"
            },
            "isAccessibleForFree": "True",
            "author": {
                "@type": "Organization",
                "@id": "http://localgov.lndo.site:8000/",
                "name": "Drush Site-Install",
                "url": "http://localgov.lndo.site:8000/"
            },
            "publisher": {
                "@type": "Organization",
                "@id": "http://localgov.lndo.site:8000/",
                "name": "Drush Site-Install",
                "url": "http://localgov.lndo.site:8000/"
            },
            "mainEntityOfPage": "http://localgov.lndo.site:8000/news/2021/lgbtq-history-month-self-awareness"
        }
    ]
}
</script>
````

That looks ok on first glance, though may require someone from product group to review if those are the correct tags.

**Comment by danchamp** [comment]
Thanks @andybroomfield 

@willguv @tom-steel would you be able to take a look at the output and validation of the schema and identify any potential issues please?

**Comment by willguv** [comment]
@danchamp it looks OK to me, but I'm not sure if it'll work for all. Is this something we can spend 10 mins on at the next Product Group?

We can circulate links in advance so people have a chance to look beforehand

**Comment by danchamp** [comment]
> @danchamp it looks OK to me, but I'm not sure if it'll work for all. Is this something we can spend 10 mins on at the next Product Group?

Definitely, that would be good. When is it please?

> We can circulate links in advance so people have a chance to look beforehand

Let me know if there's more needed than is described in this PR and I can get it prepared.

**Comment by willguv** [comment]
@danchamp 4th March. Do you received invites?

I think what's here is fine if you can walk people through it

**Comment by danchamp** [comment]
@willguv I've got it in for 10th / 24th March @ 1pm and every fortnight thereafter. Didn't get an invite for 4th March.

Happy to attend and walk through it.

**Review by andybroomfield — APPROVED** [review]
I'm happy with these to merge on a technical basis.
I think we need to rebase from master first to solve the conflicts and get the tests working.

**Pull request merged**
