### PR TITLE
Simplified promote to newsroom #32

### PR DESCRIPTION
**Pull request by ekes**
* Removes the use of 'Promote to frontpage' for featuring in the
 newsroom.
 * Adds a checkbox to (to be published) news that can add it directly into
 the existing entity reference field for listing featured items.
 * Changes view to show entity referenced featured items in the featured
 display, and exclude them from the other news.
 * Removes custom views override and logic requried to combine the
 'promoted to frontpage' with the entity reference featured.

Highlights that all will need reviewing if revisions and scheduling is
introduced. For the use case now gives editors an easy way to add
directly to featured as the 'Promote to frontpage' did, while removing
the complexity of having to maintain and combine the two different
methods of selecting articles.

### CODE REVIEW

**Comment by ekes** [comment]
@danchamp I guess it's London Council's users who are the primary recipients of this change.
@andybroomfield I'd guess you'd just hide the 'field' - or maybe you'd want to use it?
@Adnan-cds I understand Croydon would want to use an entity reference field for featuring news? So maybe an opinon?

**Comment by andybroomfield** [comment]
@ekes i guess it could be useful, I'd probably leave it unless told to remove it as it's really going into the same place as the existing ones, what matters is having an easy method of removing and replacing them (what happens when there is a more than three, I assume it just adds more, so they have to manually be deleted)

**Comment by ekes** [comment]
Failing on a completely non-related issue in the runner, restarted.

I noticed after pushing this the featured view can go as well now, as it can be replaced by the entity reference field on the newsroom itself.

**Comment by ekes** [comment]
> @ekes i guess it could be useful, I'd probably leave it unless told to remove it as it's really going into the same place as the existing ones, what matters is having an easy method of removing and replacing them (what happens when there is a more than three, I assume it just adds more, so they have to manually be deleted)

If there are three, and you add one from the node on the edit form, it adds it to the top of the entity reference field so Drupal itself pushes the bottom one off the list. (top - bottom by delta)

**Comment by danchamp** [comment]
@ekes Just one comment, otherwise looking really good.

An edge case I stumbled across - if a news article is featured but not published, it will still bump an existing featured article that is published, if there are already 3 featured articles. So the newsroom will now show only 2 featured items.

And the unpublished article still shows on the newsroom edit form, which cannot be saved without removing it (node 17 is unpublished and featured here):

image

Maybe the featured field should be unset prior to saving if the article is not published?

**Comment by ekes** [comment]
> An edge case I stumbled across - if a news article is featured but not published

The checkbox should only be visible and active if the article is to be published. So it's active when not published that's an issue.

However, for the second part. That if an item is featured, so in the entity reference field, and is then afterward unpublished, that's a problem with the way core entity reference works. We could as in Guides write some code to remove it from the entity reference. But in this case it's not going to add another item into the entity reference (which one) if you remove one. But in this case if you temporarily unpublish and republish it will still be featured. This is also just going to get way more complicated (I think I comment on this) once we get to workflow and revisions.

So for the first case, if it's possible to promote a new unpublished new news item. Then I'd say we can fix that.
For the all the other cases, including unpublishing a promoted item, maybe we make another feature to track and discuss what the ideal process would be? It's to do with the entity reference field itself more than this checkbox.

**Comment by danchamp** [comment]
> So for the first case, if it's possible to promote a new unpublished new news item. Then I'd say we can fix that.

This is the more likely scenario, so a fix would be good.

> For the all the other cases, including unpublishing a promoted item, maybe we make another feature to track and discuss what the ideal process would be? It's to do with the entity reference field itself more than this checkbox.

I don't think this is worth the effort, it's an unlikely scenario and there's a degree of editor responsibility required.

**Comment by ekes** [comment]
>>  So for the first case, if it's possible to promote a new unpublished new news item. Then I'd say we can fix that.
> This is the more likely scenario, so a fix would be good.

I can't recreate.

The checkbox isn't shown if the node isn't to be published: https://github.com/localgovdrupal/localgov_news/pull/33/files#diff-a737f4209cef9e4858c99cea58e1bad2969012051e4f280ce16c8362bf9d854aR127
And on submission it checks its status: https://github.com/localgovdrupal/localgov_news/pull/33/files#diff-a737f4209cef9e4858c99cea58e1bad2969012051e4f280ce16c8362bf9d854aR149

So it would seem that the first case is covered?

**Comment by danchamp** [comment]
> I can't recreate.

Sorry @ekes, I can confirm this was caused by LocalGov Workflow being enabled, and me not reading your notes carefully enough. Without workflow it works as designed.

**Review by danchamp — APPROVED** [review]

**Comment by ekes** [comment]
> Without workflow it works as designed.

For with I've created #38

**Pull request merged**
