### PR TITLE
Don't create a newsroom by default.

### PR DESCRIPTION
**Pull request by ekes**
* Following the same pattern as Directories.
 * For Microsites it's not desired to have a node created on the master
   site.

### CODE REVIEW

**Comment by ekes** [comment]
Ah! We'll have to update the tests to add a newsroom.

**Comment by andybroomfield** [comment]
Are we sure we don't need a newsroom? 

I'm not sure how the news feature works without one.

We should add a warning (which microsites main site could supress?) that states that content designers should set up at least one newsroom before creating news articles.

**Comment by ekes** [comment]
> We should add a warning (which microsites main site could supress?) that states that content designers should set up at least one newsroom before creating news articles.

Directories could do the same as it's also needed to do that there.

**Comment by stephen-cox** [comment]
If we remove the automatic creation of a default news rooms then we also need to update the content designer docs: https://docs.localgovdrupal.org/content/features/news.html

If it's felt we do need a default news room then we could check the enabled profile and only add it when this is `localgov`.

This feels a bit like a content question rather than a developer question. Is it worth double checking the behavior with the product group?

**Comment by willguv** [comment]
@stephen-cox the next PG isn't for 3 weeks, so how about posting in #group-product or #general?

**Comment by finnlewis** [comment]
@andybroomfield was wondering whether we should add more documentation within the install process and / or status site.

@ekes has updated the README with minimal instructions.

@msayoung likes the idea of adding some inline help for content designers: if no newsroom has been created, possibly add a message on the news content. 

@andybroomfield suggests adding an issue to cover better documentation - inline docss and / or status page etc. We should also follow the same pattern on directories.

Otherwise no concerns with merging this now!

**Review by finnlewis — APPROVED** [review]
Yay!

**Pull request merged**
